version: 2
jobs:
  build:
    working_directory: ~/weather-10kb
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: remove-lock
          command: rm ./package-lock.json
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules

      - run:
          name: run-tests
          command: 'npx nyc mocha'

      - run:
          name: test-reporter
          command: 'npx nyc -r html --report-dir reports/coverage/html mocha --reporter=xunit --reporter-options output=reports/test-results.xml'
      - run:
          name: generate-coverage
          command: 'npx nyc report --reporter=text-lcov > reports/coverage/coverage.lcov'
      - store_test_results:
          path: reports/test-results.xml
      - store_artifacts:
          path: reports/test-results.xml
          prefix: tests
      - store_artifacts:
          path: reports/coverage/coverage.lcov
          prefix: coverage
